"""
Research-metrics use-case — provenance-explicit, auto-switching.

  * CNN metrics: VERIFIED, read from evaluation/cnn_<ver>/ (regenerated by
    regenerate_cnn_evaluation.py from the saved test-set arrays).
  * v5 metrics: if evaluation/v5/metrics.json exists (produced by
    evaluate_v5.py), it is used as the VERIFIED v5 evaluation and the app shows
    it automatically. Until then, the DOCUMENTED thesis values are returned,
    flagged as not experimentally reproduced.

Nothing here is hand-entered except the explicitly-flagged v5 documented values,
which are only used while no v5 artefact exists.
"""

import csv
import json

from api.schemas import CurvePoint, ModelMetrics, PerSpeciesMetric, ResearchMetricsOut
from birddash import config

# DOCUMENTED (not yet reproduced) v5 figures — README/thesis. Used ONLY as a
# fallback while evaluation/v5/ does not exist.
V5_AUPRC_DOCUMENTED = 0.98
V5_AUROC_DOCUMENTED = 0.99
V5_NOTE_DOCUMENTED = (
    "Documented research values (thesis/README). Not yet reproduced from stored "
    "evaluation artefacts — the v5 training used an internal split that was not "
    "persisted. Run evaluate_v5.py to generate a recording-level held-out "
    "evaluation; the app will then show verified v5 metrics automatically."
)
V5_NOTE_VERIFIED = (
    "Verified — recording-level held-out evaluation reproduced by evaluate_v5.py "
    "(a classifier retrained on the train split, evaluated on unseen recordings)."
)

CNN_VERSION = "v2"


def _read_curve(path, x_key, y_key) -> list[CurvePoint]:
    if not path.exists():
        return []
    with open(path) as f:
        return [CurvePoint(x=float(r[x_key]), y=float(r[y_key])) for r in csv.DictReader(f)]


def _load_metrics(dir_name: str) -> ModelMetrics | None:
    d = config.BASE_DIR / "evaluation" / dir_name
    mfile = d / "metrics.json"
    if not mfile.exists():
        return None
    m = json.loads(mfile.read_text())
    return ModelMetrics(
        version=m.get("model", dir_name), description=m.get("description", ""),
        accuracy=m["accuracy"], macro_f1=m["macro_f1"], weighted_f1=m["weighted_f1"],
        macro_auroc=m["macro_auroc"], macro_auprc=m["macro_auprc"],
        per_species=[PerSpeciesMetric(**p) for p in m["per_species"]],
        roc_curve=_read_curve(d / "roc_curve.csv", "fpr", "tpr"),
        pr_curve=_read_curve(d / "pr_curve.csv", "recall", "precision"),
        provenance=m.get("provenance", {}),
    )


def research_metrics() -> ResearchMetricsOut:
    v4 = config.BASE_DIR / "evaluation" / "cnn_v4" / "metrics.json"
    v4_acc = json.loads(v4.read_text())["accuracy"] if v4.exists() else None

    v5 = _load_metrics("v5")   # verified evaluation, if it exists
    return ResearchMetricsOut(
        cnn=_load_metrics(f"cnn_{CNN_VERSION}"),
        cnn_recording_level_accuracy=v4_acc,
        v5_metrics=v5,
        v5_auprc=v5.macro_auprc if v5 else V5_AUPRC_DOCUMENTED,
        v5_auroc=v5.macro_auroc if v5 else V5_AUROC_DOCUMENTED,
        v5_verified=v5 is not None,
        v5_note=V5_NOTE_VERIFIED if v5 else V5_NOTE_DOCUMENTED,
    )
