"""initial core schema

Revision ID: 148afca23aa2
Revises: 
Create Date: 2026-07-16 21:39:31.893539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '148afca23aa2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_key'), 'models', ['key'], unique=True)
    op.create_table('organisations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisations_slug'), 'organisations', ['slug'], unique=True)
    op.create_table('species',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=False),
    sa.Column('scientific_name', sa.String(length=255), nullable=True),
    sa.Column('class_index', sa.Integer(), nullable=True),
    sa.Column('conservation_status', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_index')
    )
    op.create_index(op.f('ix_species_common_name'), 'species', ['common_name'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('result_kind', sa.String(length=32), nullable=True),
    sa.Column('result_id', sa.Uuid(), nullable=True),
    sa.Column('error', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_organisation_id'), 'jobs', ['organisation_id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_organisation_id'), 'sites', ['organisation_id'], unique=False)
    op.create_table('sensors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_site_id'), 'sensors', ['site_id'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('sensor_id', sa.Uuid(), nullable=True),
    sa.Column('source_path', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('media_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_path')
    )
    op.create_index(op.f('ix_recordings_filename'), 'recordings', ['filename'], unique=False)
    op.create_index(op.f('ix_recordings_organisation_id'), 'recordings', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_recordings_sensor_id'), 'recordings', ['sensor_id'], unique=False)
    op.create_index(op.f('ix_recordings_site_id'), 'recordings', ['site_id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recording_id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_model_id'), 'analyses', ['model_id'], unique=False)
    op.create_index(op.f('ix_analyses_recording_id'), 'analyses', ['recording_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_recording_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_model_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_recordings_site_id'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_sensor_id'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_organisation_id'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_filename'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_sensors_site_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_sites_organisation_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_jobs_organisation_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_species_common_name'), table_name='species')
    op.drop_table('species')
    op.drop_index(op.f('ix_organisations_slug'), table_name='organisations')
    op.drop_table('organisations')
    op.drop_index(op.f('ix_models_key'), table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###
