"use client";

import { useState } from "react";

import { Skeleton } from "@/components/ui/skeleton";
import { API_BASE } from "@/lib/config";

/**
 * Server-rendered mel spectrogram (PNG), generated by birddash.audio — the
 * same pipeline the Streamlit app used. Reliable and consistent, unlike
 * client-side FFT.
 */
export function SpectrogramViewer({ recordingId }: { recordingId: string }) {
  const [loaded, setLoaded] = useState(false);
  const [failed, setFailed] = useState(false);
  const src = `${API_BASE}/api/v1/recordings/${recordingId}/spectrogram`;

  return (
    <div className="relative min-h-[220px]">
      {!loaded && !failed && <Skeleton className="absolute inset-0 h-full w-full" />}
      {failed ? (
        <p className="py-8 text-center text-sm text-muted-foreground">Spectrogram unavailable.</p>
      ) : (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={src}
          alt="Mel spectrogram"
          className="w-full rounded-md"
          onLoad={() => setLoaded(true)}
          onError={() => setFailed(true)}
        />
      )}
    </div>
  );
}
